In [1]:
import pandas as pd
import numpy as np

In [2]:
data_path = "/home/joseph/Dev/rtw19-hacks/hackathon-packet/data/"
data = pd.read_csv(data_path + "train.csv", index_col="idx")

/home/joseph/.virtualenvs/mldis/local/lib/python2.7/site-packages/numpy/lib/arraysetops.py:571: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [3]:
data.shape

(2019036, 37)

In [4]:
# The columns of our dataset and their types
data.dtypes

DC_ZIPCODE                               int64
Invoice_Year                             int64
Invoice_Week                             int64
CATEGORY                                object
TIER                                    object
SPEED_RATING_CODE                       object
RIM_DIAMETER_SIZE_CODE                 float64
WIDTH                                  float64
HEIGHT                                 float64
AVG_UNIT_WEIGHT                        float64
Invoice_Month                            int64
SELLING_PRICE                          float64
Monthly_Top_1_Customer_Zip               int64
Monthly_Top_2_Customer_Zip               int64
Monthly_Top_3_Customer_Zip             float64
Monthly_Top_4_Customer_Zip             float64
Monthly_Top_5_Customer_Zip             float64
Monthly_Top_6_Customer_Zip             float64
Monthly_Top_7_Customer_Zip             float64
Monthly_Top_8_Customer_Zip             float64
Monthly_Top_9_Customer_Zip             float64
Monthly_Top_10_Customer_Zip            float64
Monthly_Top_1_Customer_Total_Sales     float64
Monthly_Top_2_Customer_Total_Sales     float64
Monthly_Top_3_Customer_Total_Sales     float64
Monthly_Top_4_Customer_Total_Sales     float64
Monthly_Top_5_Customer_Total_Sales     float64
Monthly_Top_6_Customer_Total_Sales     float64
Monthly_Top_7_Customer_Total_Sales     float64
Monthly_Top_8_Customer_Total_Sales     float64
Monthly_Top_9_Customer_Total_Sales     float64
Monthly_Top_10_Customer_Total_Sales    float64
UNITS                                    int64
zip_code                               float64
totalpopulation                        float64
state                                   object
median_household_income                float64
dtype: object

### Mean Units Sold vs Year-Month-Week

In [18]:
data[['Invoice_Year','Invoice_Month','Invoice_Week','UNITS']].groupby(['Invoice_Year','Invoice_Month','Invoice_Week']).mean()

                                            UNITS
Invoice_Year Invoice_Month Invoice_Week
2016         1             1             8.537060
                           2             8.366429
                           3             8.610812
                           4             8.146528
                           53            4.803726
             2             5             8.083539
                           6             8.603592
                           7             8.665693
                           8             8.670505
                           9             5.258995
             3             9             7.305718
                           10            8.572752
                           11            8.412971
                           12            8.193862
                           13            6.993718
             4             13            5.454391
                           14            8.285921
                           15            8.255617
                           16            8.078258
                           17            8.184047
             5             17            5.515152
                           18            8.165196
                           19            8.020242
                           20            8.129051
                           21            8.261016
                           22            5.237272
             6             22            6.761143
                           23            8.195240
                           24            8.168305
                           25            8.181525
...                                           ...
2017         7             28            8.052065
                           29            7.989306
                           30            8.091642
                           31            4.985462
             8             31            7.164072
                           32            8.147108
                           33            8.075861
                           34            7.980211
                           35            6.977901
             9             35            5.485142
                           36            8.083182
                           37            8.231921
                           38            8.215611
                           39            8.511850
             10            39            5.920000
                           40            8.426014
                           41            8.434348
                           42            8.417249
                           43            8.544437
                           44            6.132149
             11            44            6.666925
                           45            8.970002
                           46            8.849852
                           47            7.943837
                           48            6.969968
             12            48            5.346777
                           49            8.421998
                           50            8.494808
                           51            8.436431
                           52            8.225885

[125 rows x 1 columns]

### Mean Units Sold vs Distribution Center Zipcode

In [25]:
data[['DC_ZIPCODE','UNITS']].groupby(['DC_ZIPCODE']).mean()

                UNITS
DC_ZIPCODE
11717        8.377861
12206        7.566470
14624        7.990034
15026       10.666697
20110        8.381832
21220        7.612083
21227        8.386164
22802        8.219180
24019        7.598214
24382        8.576280
25159        8.515561
27215        8.089876
27893        8.894643
28070       -5.151515
28214        9.275691
28311        8.019368
28403        7.445012
28704        7.595117
29201        6.705625
29406        5.406060
29501        7.752602
29662        8.504971
30084        6.380065
30294        6.302985
30909        6.310808
31008        6.884472
32254        7.026082
32303        6.388138
32514        6.371894
32824        7.573515
...               ...
75006        7.124417
77067        7.843255
77489        7.258030
77705        6.984876
78501        6.976559
78753        7.125050
79118        8.252192
79382        7.787799
79928        7.187452
80216        8.850867
80916        7.913483
81505        8.099456
83687        7.043856
85007        8.449470
87113        7.569391
89115        7.199684
89434        8.323247
90221        6.788944
90670        7.343385
91730        7.794003
91911        7.629577
93021        7.384214
93263        7.454010
93725        7.902589
94801        7.323451
95131        8.335987
95838        8.091332
97203        7.961068
97502        7.129761
98001        7.520135

[92 rows x 1 columns]

### Mean Units Sold vs Unique Tires Offered

In [28]:
data[['CATEGORY','TIER','SPEED_RATING_CODE','RIM_DIAMETER_SIZE_CODE','UNITS']].groupby(['CATEGORY','TIER','SPEED_RATING_CODE','RIM_DIAMETER_SIZE_CODE']).mean()

                                                                    UNITS
CATEGORY       TIER   SPEED_RATING_CODE RIM_DIAMETER_SIZE_CODE
AT Mud Utility Tier 1 Q                 17.0                     6.000000
                      R                 15.0                     4.000000
                                        16.0                    -1.636364
                                        17.0                     0.000000
                                        18.0                     0.000000
                                        20.0                     2.000000
                      S                 15.0                     2.000000
                                        16.0                     2.000000
                                        17.0                     5.179487
                                        20.0                     3.123288
                      T                 15.0                     2.000000
                                        16.0                     0.000000
                                        17.0                     1.769231
                                        20.0                    -2.000000
               Tier 2 H                 16.0                     5.000000
                      N                 16.0                     2.000000
                      P                 17.0                     3.818182
                      Q                 15.0                     1.904762
                                        16.0                     3.384615
                                        17.0                     4.222222
                                        18.0                     2.000000
                      R                 15.0                     2.000000
                                        16.0                     9.415929
                                        17.0                     7.200000
                      S                 15.0                     0.333333
                                        16.0                     4.500000
                                        17.0                     1.600000
                                        20.0                     4.000000
                      T                 17.0                     3.818182
               Tier 3 N                 16.0                     5.857143
...                                                                   ...
Winter         Tier 2 T                 14.0                     6.538462
                                        15.0                     7.618406
                                        16.0                     9.243740
                                        17.0                     8.629475
                                        18.0                     7.460870
                                        19.0                     6.610619
                                        20.0                     5.879518
                                        21.0                     3.500000
                      V                 16.0                     7.698020
                                        17.0                     6.415094
                                        18.0                     7.937173
                                        19.0                     0.000000
                                        20.0                     4.800000
               Tier 3 Q                 14.0                    -2.000000
                                        15.0                     7.363958
                                        16.0                    10.409091
                                        17.0                    10.094701
                      R                 17.0                     7.543147
                                        18.0                    10.090476
                      S                 14.0                     7.685509
                                        15.0                     8.195576
                                        16.0                     9.307506
                                        17.0                    10.439060
                                        18.0                     7.762887
                                        20.0                     8.645161
                      T                 14.0                     7.455331
                                        15.0                     8.814371
                                        16.0                     9.919880
                                        17.0                     9.960670
                                        18.0                     9.646259

[763 rows x 1 columns]