In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
import sklearn as sk

In [14]:
from sklearn.datasets import load_iris
iris = load_iris()
attributes = iris.feature_names
X = iris.data
y = iris.target

In [29]:
#sb.pairplot(pd.DataFrame(X),hue=y)
df = pd.DataFrame(X, columns=attributes)
df['Species'] = y

       0
0    5.1
1    3.5
2    1.4
3    0.2
4    4.9
5    3.0
6    1.4
7    0.2
8    4.7
9    3.2
10   1.3
11   0.2
12   4.6
13   3.1
14   1.5
15   0.2
16   5.0
17   3.6
18   1.4
19   0.2
20   5.4
21   3.9
22   1.7
23   0.4
24   4.6
25   3.4
26   1.4
27   0.3
28   5.0
29   3.4
..   ...
720  2.0
721  2.0
722  2.0
723  2.0
724  2.0
725  2.0
726  2.0
727  2.0
728  2.0
729  2.0
730  2.0
731  2.0
732  2.0
733  2.0
734  2.0
735  2.0
736  2.0
737  2.0
738  2.0
739  2.0
740  2.0
741  2.0
742  2.0
743  2.0
744  2.0
745  2.0
746  2.0
747  2.0
748  2.0
749  2.0

[750 rows x 1 columns]